# Generated by Django 6.0.6 on 2026-06-08 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_stocktransfer_purchaseorder_goodsreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature parameter in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Humidity parameter in %', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storage_locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='risk_probability',
            field=models.FloatField(default=0.0, help_text='Calculated risk of expiry (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='risk_tier',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='products.storagelocation'),
        ),
    ]
