[project]
name = "marcus-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloudinary>=1.44.2",
    "dj-database-url>=3.1.2",
    "django>=6.0.6",
    "django-allauth>=65.18.0",
    "django-cloudinary-storage>=0.3.0",
    "djlint>=1.40.6",
    "dotenv>=0.9.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "python-decouple>=3.8",
    "reportlab>=4.5.1",
    "scikit-learn>=1.9.0",
    "whitenoise>=6.12.0",
    "psycopg[binary]",
    "resend",
    "gunicorn>=26.0.0",
]
