# Generated by Django 6.0.6 on 2026-06-08 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('products', '0010_storagelocation_stockbatch_risk_probability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('critical_threshold_days', models.PositiveIntegerField(default=7, help_text='Expiry within these days is Critical')),
                ('high_threshold_days', models.PositiveIntegerField(default=30, help_text='Expiry within these days is High')),
                ('medium_threshold_days', models.PositiveIntegerField(default=60, help_text='Expiry within these days is Medium')),
                ('recipient_emails', models.TextField(default='admin@marcusstore.com', help_text='Comma-separated emails')),
                ('recipient_phones', models.TextField(default='+1234567890', help_text='Comma-separated phone numbers')),
                ('escalation_hours', models.PositiveIntegerField(default=24, help_text='Hours before escalation if unacknowledged')),
                ('escalation_email', models.EmailField(default='manager@marcusstore.com', help_text='Escalation email address', max_length=254)),
                ('sms_provider_url', models.URLField(default='https://api.sms-gateway.com/send', help_text='SMS gateway API URL')),
                ('sms_api_key', models.CharField(blank=True, help_text='SMS provider API key', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_configurations',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_tier', models.CharField(max_length=20)),
                ('risk_probability', models.FloatField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='generated', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.stockbatch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
