# Generated by Django 6.0.6 on 2026-06-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alertconfiguration_alertlog'),
        ('products', '0010_storagelocation_stockbatch_risk_probability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_days', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_milestones', to='products.stockbatch')),
            ],
            options={
                'db_table': 'expiry_milestones',
                'unique_together': {('batch', 'milestone_days')},
            },
        ),
    ]
