# Generated by Django 6.0.6 on 2026-08-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_expirymilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, help_text='Cloudinary API Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='cloudinary_api_secret',
            field=models.CharField(blank=True, help_text='Cloudinary API Secret', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='cloudinary_cloud_name',
            field=models.CharField(blank=True, help_text='Cloudinary Cloud Name', max_length=255, null=True),
        ),
    ]
